import type { WebsiteTemplate } from "./types"

// Define high-quality website templates
export const websiteTemplates: WebsiteTemplate[] = [
  {
    id: "modern-portfolio",
    name: "Modern Portfolio",
    category: "portfolio",
    description: "A sleek, professional portfolio website with smooth animations and modern design",
    structure: {
      sections: [
        "Hero section with animated text and CTA",
        "About section with skills grid",
        "Projects showcase with filtering",
        "Experience timeline",
        "Contact form with validation",
        "Footer with social links",
      ],
      features: [
        "Smooth scroll navigation",
        "Dark/light mode toggle",
        "Responsive grid layouts",
        "Intersection Observer animations",
        "Form validation",
        "Mobile-first design",
      ],
      designPrinciples: [
        "Minimalist design with focus on content",
        "High contrast for readability",
        "Consistent spacing using 8px grid",
        "Typography hierarchy with 3 font sizes max",
        "Accent color for CTAs and highlights",
        "Subtle animations on scroll",
      ],
    },
    codePatterns: {
      html: [
        "Semantic HTML5 structure",
        "ARIA labels for accessibility",
        "Meta tags for SEO",
        "Structured data markup",
        "Progressive enhancement",
      ],
      css: [
        "CSS Grid for layouts",
        "CSS custom properties for theming",
        "Clamp() for responsive typography",
        "Container queries where applicable",
        "Smooth transitions and transforms",
        "Mobile-first media queries",
      ],
      javascript: [
        "Intersection Observer for animations",
        "Event delegation for performance",
        "Debounced scroll events",
        "Form validation with regex",
        "LocalStorage for theme preference",
        "Lazy loading for images",
      ],
    },
    bestPractices: [
      "Performance: Optimize images, minify code, lazy load",
      "Accessibility: WCAG 2.1 AA compliance",
      "SEO: Meta tags, structured data, semantic HTML",
      "Security: Input sanitization, HTTPS",
      "UX: Fast load times, smooth interactions",
    ],
    examplePrompt:
      "Create a modern portfolio website for a software developer with hero section, projects showcase, skills grid, and contact form",
  },
  {
    id: "saas-landing",
    name: "SaaS Landing Page",
    category: "landing",
    description: "High-converting SaaS landing page with compelling copy and clear CTAs",
    structure: {
      sections: [
        "Navigation with sticky header",
        "Hero with value proposition",
        "Features grid with icons",
        "Benefits section with testimonials",
        "Pricing table with toggle",
        "FAQ accordion",
        "CTA section",
        "Footer with links",
      ],
      features: [
        "Sticky navigation on scroll",
        "Animated statistics counters",
        "Interactive pricing calculator",
        "Testimonial carousel",
        "FAQ accordion",
        "Newsletter signup",
        "Social proof elements",
      ],
      designPrinciples: [
        "Clear visual hierarchy",
        "Consistent brand colors",
        "Whitespace for clarity",
        "F-pattern layout",
        "Contrast for CTAs",
        "Trust signals throughout",
      ],
    },
    codePatterns: {
      html: [
        "Schema markup for business",
        "Microdata for reviews",
        "Form elements with labels",
        "Button hierarchy (primary/secondary)",
        "Loading states for forms",
      ],
      css: [
        "CSS Grid for pricing tables",
        "Flexbox for navigation",
        "Backdrop filters for depth",
        "Gradient overlays",
        "Box shadows for elevation",
        "Hover states for interactivity",
      ],
      javascript: [
        "Smooth scroll to sections",
        "Pricing toggle functionality",
        "Form submission handling",
        "Analytics event tracking",
        "Countdown timers for urgency",
        "Exit intent popups",
      ],
    },
    bestPractices: [
      "Conversion: Clear CTAs, social proof, urgency",
      "Performance: Critical CSS, async scripts",
      "Trust: Security badges, testimonials, guarantees",
      "Mobile: Touch-friendly buttons, readable text",
      "Analytics: Event tracking, conversion goals",
    ],
    examplePrompt:
      "Create a SaaS landing page for a project management tool with hero section, features grid, pricing table, testimonials, and FAQ",
  },
  {
    id: "ecommerce-store",
    name: "E-commerce Store",
    category: "ecommerce",
    description: "Modern e-commerce website with product grid, cart functionality, and checkout flow",
    structure: {
      sections: [
        "Header with search and cart",
        "Hero banner with promotions",
        "Featured products carousel",
        "Product categories grid",
        "Product listing with filters",
        "Product detail pages",
        "Shopping cart sidebar",
        "Checkout process",
        "Footer with policies",
      ],
      features: [
        "Product search with filters",
        "Shopping cart with localStorage",
        "Product image galleries",
        "Size/color selectors",
        "Wishlist functionality",
        "Quick view modals",
        "Related products",
        "Reviews and ratings",
      ],
      designPrinciples: [
        "Product-focused design",
        "Clear pricing display",
        "Trust badges visible",
        "Easy navigation",
        "Mobile shopping optimized",
        "Fast image loading",
      ],
    },
    codePatterns: {
      html: [
        "Product schema markup",
        "Breadcrumb navigation",
        "Image alt texts for SEO",
        "Form validation messages",
        "Loading skeletons",
      ],
      css: [
        "Grid layouts for products",
        "Aspect ratio boxes for images",
        "Custom select dropdowns",
        "Progress indicators",
        "Toast notifications",
        "Modal overlays",
      ],
      javascript: [
        "Cart state management",
        "Product filtering logic",
        "Image zoom functionality",
        "Add to cart animations",
        "Quantity selectors",
        "Price calculations",
      ],
    },
    bestPractices: [
      "UX: Easy checkout, clear CTAs, product info",
      "Performance: Image optimization, lazy loading",
      "Trust: Secure badges, return policy, reviews",
      "Mobile: Touch gestures, mobile payments",
      "SEO: Product schema, meta descriptions",
    ],
    examplePrompt:
      "Create an e-commerce website for a clothing store with product grid, filters, shopping cart, and modern design",
  },
  {
    id: "restaurant-website",
    name: "Restaurant Website",
    category: "hospitality",
    description: "Elegant restaurant website with menu, reservations, and ambiance showcase",
    structure: {
      sections: [
        "Hero with restaurant imagery",
        "About section with story",
        "Menu with categories",
        "Gallery of dishes/ambiance",
        "Reservation form",
        "Location with map",
        "Hours and contact",
        "Reviews section",
      ],
      features: [
        "Interactive menu with prices",
        "Table reservation system",
        "Image gallery with lightbox",
        "Google Maps integration",
        "Social media feeds",
        "Special offers banner",
        "Newsletter signup",
      ],
      designPrinciples: [
        "Appetizing food photography",
        "Elegant typography",
        "Warm color palette",
        "Easy-to-read menus",
        "Mobile-friendly design",
        "Fast loading images",
      ],
    },
    codePatterns: {
      html: [
        "Restaurant schema markup",
        "Menu structured data",
        "Reservation form fields",
        "Address microformat",
        "Image galleries",
      ],
      css: [
        "Parallax scrolling effects",
        "Menu card designs",
        "Image hover effects",
        "Responsive tables",
        "Print styles for menus",
        "Custom fonts for branding",
      ],
      javascript: [
        "Reservation form validation",
        "Gallery lightbox",
        "Smooth scroll navigation",
        "Menu filtering",
        "Map initialization",
        "Opening hours display",
      ],
    },
    bestPractices: [
      "Local SEO: Schema markup, Google My Business",
      "Mobile: Click-to-call, easy navigation",
      "Performance: Optimized images, fast load",
      "Accessibility: Screen reader friendly menus",
      "Conversion: Clear CTAs for reservations",
    ],
    examplePrompt:
      "Create a restaurant website with elegant design, menu display, reservation system, gallery, and location information",
  },
  {
    id: "corporate-business",
    name: "Corporate Business",
    category: "business",
    description: "Professional corporate website with services, team, and company information",
    structure: {
      sections: [
        "Professional header with logo",
        "Hero with company message",
        "Services/solutions grid",
        "About company section",
        "Team members showcase",
        "Client logos/testimonials",
        "Case studies",
        "Contact information",
        "Footer with sitemap",
      ],
      features: [
        "Multi-level navigation",
        "Service detail pages",
        "Team member profiles",
        "Case study layouts",
        "Contact forms",
        "Office locations",
        "Career opportunities",
        "News/blog section",
      ],
      designPrinciples: [
        "Professional color scheme",
        "Clean, corporate design",
        "Trustworthy appearance",
        "Clear information hierarchy",
        "Consistent branding",
        "Accessible design",
      ],
    },
    codePatterns: {
      html: [
        "Organization schema markup",
        "Breadcrumb navigation",
        "Contact information markup",
        "Team member cards",
        "Service descriptions",
      ],
      css: [
        "Corporate color variables",
        "Professional typography",
        "Card-based layouts",
        "Hover effects for links",
        "Responsive tables",
        "Print-friendly styles",
      ],
      javascript: [
        "Multi-level menu navigation",
        "Form validation and submission",
        "Smooth scroll to sections",
        "Tab interfaces",
        "Accordion for FAQs",
        "Cookie consent banner",
      ],
    },
    bestPractices: [
      "Trust: Professional design, client logos, certifications",
      "SEO: Service pages, location pages, schema markup",
      "Accessibility: WCAG compliance, keyboard navigation",
      "Performance: Optimized assets, caching strategies",
      "Security: SSL, secure forms, privacy policy",
    ],
    examplePrompt:
      "Create a corporate website for a consulting firm with services showcase, team section, case studies, and professional design",
  },
]

// Export all template IDs for easy access
export const templateIds = websiteTemplates.map((t) => t.id)
